
title: Tianfu Li's Homepage
page-top-title: Tianfu Li (李天福)
top-section-bg-text: Welcome to my Homepage
home-subtitle: Tianfu Li&ensp;|&ensp;李天福
copyright-text: '&copy; Tianfu Li 2024. All Rights Reserved.'
